services:
  db:
    image: postgres:15
    container_name: blog-system_postgres
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data
    networks:
      - blog_network

pgadmin:
    image: dpage/pgadmin4:latest
    container_name: blog-system_pgadmin
    environment:
      PGLADMIN_DEFAULT_EMAIL: admin@example.com
      PGLADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - blog_network

web:
    build: .
    container_name: blog-system_webapp
    ports:
      - "8503:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://admin:password@db:5432/blog_db
    volumes:
      - .:/app
    networks:
      - blog_network

volumes:
  blog_data:

networks:
  blog_network:
    driver: bridge